<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="addModalLabel"><?php echo $uid ? "编辑" : "添加"; ?>IP</h4>
</div>
<div class="modal-body">
    <form id="ip-form">
        <div class="form-group input-group  input-control">
            <span class="input-group-addon">IP地址</span>
            <input type="text" class="form-control" id="ip" name="ip"
                   placeholder="格式示例: 127.0.0.1"
                   onBlur="checkIp(this.value);"
                   value="<?= $ip; ?>">
        </div>
        <span class="span-name" id="check-ip"></span>

        <input type="hidden" name="prev_ip" value="<?php echo $ip; ?>"/>

        <div class="form-group input-group  input-control">
            <span class="input-group-addon">&nbsp;描述&nbsp;&nbsp;</span>
            <input type="text" class="form-control" id="description" name="description" placeholder="示例: 办公室"
                   value="<?= $description; ?>">
        </div>
    </form>
</div>
<div class="modal-footer">
    <span class="tips" id="atip"></span>
    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
    <button type="button" id="save" class="btn btn-primary">保存</button>
</div>
<script>
    $(document).ready(function () {
        $('#save').click(function () {
            var ip = $('#ip'), description = $('#description');
            if (!ip.val().trim()) {
                alert('请填写ip');
                ip.focus();
                return;
            }
            if (!description.val().trim()) {
                alert('请填写备注');
                description.focus();
                return;
            }
            $.ajax({
                cache: true,
                type: "POST",
                url: url("/sysconfig/saveIpWhiteList"),
                data: $('#ip-form').serialize(),
                dataType: 'json',
                error: function (data) {
                    alert('系统异常，请稍后再试！');
                },
                success: function (data) {
                    if (data.retcode == 2000000) {
                        refresh();
                    }
                }
            });
        });

    });

    function checkIp(ip) {
        if ('<?= $ip; ?>' == ip) {
            return;
        }
        $.get(url("/sysconfig/isIpExist"), {ip: ip},
            function (data) {
                if (data.retcode == 2000000) {
                    $('#check-ip').html('');
                } else {
                    $('#check-ip').html('IP已存在');
                }
            }, "json");
    }
</script>
