<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title">
            <a href="/Admin/welcome/index" class="site_title">
                <i class="fa fa-cloud"></i>
                <span><?php echo ADMIN_SYS_NAME; ?></span>
            </a>
        </div>
        <div class="clearfix"></div>

        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <?php foreach ((array)$menu as $firstLvName => $secondLvs) { ?>
                        <li>
                            <a><i class="fa fa-th-list"></i><span class="fa-title"><?= $firstLvName ?></span><span
                                    class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <?php foreach ((array)$secondLvs as $nav) { ?>
                                    <li><a href="<?= $nav['link'] ?>"><?= $nav['name'] ?></a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a href="/Admin/login/logout" data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                       aria-expanded="false">
                        <?= $_SESSION['name'] ?>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="/Admin/user/editUserInfo?uid=<?= $_SESSION['uid']?>">个人信息</a></li>
                        <li><a href="/Admin/login/logout"><i class="fa fa-sign-out pull-right"></i>登出</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
