<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>访问提示</title>
    <?php include(ADMIN_BASE_TPL_PATH . "/inc/include.phtml"); ?>
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
            <div class="col-middle">
                <div class="text-center">
                    <h1 class="error-number"><?= $retcode; ?></h1>
                    <h2><?= $msg; ?><p><a href="<?= $_SERVER['HTTP_REFERER'] ?>">返回上一页</a></p></h2>
                </div>
            </div>
        </div>
        <!-- /page content -->
    </div>
</div>
</body>

<script>
    if ($('a').length > 1) {
        $('a:last').remove();
    }
    url = $('a').attr('href');
    if (url) {
        setTimeout(function () {
            window.location.href = $('a').attr('href');
        }, 3000);
    }
</script>
</html>